Flow for internal app sharing

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -61,3 +61,29 @@ jobs:
           type: experimental
           FASTLANE_GOOGLE_SERVICE_ACCOUNT: ${{ secrets.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}
           BUGSNAG_KEY: ${{ secrets.BUGSNAG_KEY }}
+
+  upload-internal:
+    name: Upload Internal
+    runs-on: ubuntu-latest
+    needs: build-android
+    if: ${{ inputs.type == 'experimental' }}
+    steps:
+      - name: Validate type input
+        run: |
+          if [[ "${{ inputs.type }}" != "experimental" ]]; then
+            echo "❌ Invalid input: 'type' must be 'experimental'"
+            exit 1
+          fi
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Checkout and Setup Node
+        uses: ./.github/actions/setup-node
+      
+      - name: Upload Android
+        uses: ./.github/actions/upload-internal-android
+        with:
+          type: experimental
+          FASTLANE_GOOGLE_SERVICE_ACCOUNT: ${{ secrets.FASTLANE_GOOGLE_SERVICE_ACCOUNT }}
+          BUGSNAG_KEY: ${{ secrets.BUGSNAG_KEY }}
