Changes in flow script

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -6,32 +6,20 @@ on:
       type:
         type: string
         required: true
-    secrets:
-      BUGSNAG_KEY:
-        required: true
-      KEYSTORE_EXPERIMENTAL:
-        required: true
-      KEYSTORE_EXPERIMENTAL_BASE64:
-        required: true
-      KEYSTORE_EXPERIMENTAL_PASSWORD:
-        required: true
-      KEYSTORE_EXPERIMENTAL_ALIAS:
-        required: true
-      GOOGLE_SERVICES_ANDROID:
-        required: true
-      FASTLANE_GOOGLE_SERVICE_ACCOUNT:
-        required: true
 
 jobs:
   build-android:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate type input
+        run: |
+          if [[ "${{ inputs.type }}" != "official" && "${{ inputs.type }}" != "experimental" ]]; then
+            echo "❌ Invalid input: 'type' must be 'official' or 'experimental'"
+            exit 1
+          fi
+
       - name: Checkout Repository
         uses: actions/checkout@v4
-
-      - name: Log the run number
-        run: |
-          echo "Run number: ${{ github.run_number }}"
 
       - name: Log the secrets
         run: |
diff --git a/.github/workflows/build-ios.yml b/.github/workflows/build-ios.yml
--- a/.github/workflows/build-ios.yml
+++ b/.github/workflows/build-ios.yml
@@ -6,29 +6,19 @@ on:
       type:
         type: string
         required: true
-    secrets:
-      APP_STORE_CONNECT_API_KEY_BASE64:
-        required: true
-      BUGSNAG_KEY:
-        required: true
-      MATCH_KEYCHAIN_NAME:
-        required: true
-      MATCH_KEYCHAIN_PASSWORD:
-        required: true
-      MATCH_PASSWORD:
-        required: true
-      APP_STORE_CONNECT_API_KEY_ID:
-        required: true
-      APP_STORE_CONNECT_API_KEY_ISSUER_ID:
-        required: true
-      FASTLANE_REPO_PAT:
-        required: true
 
 jobs:
   ios-build:
     runs-on: macos-15
 
     steps:
+      - name: Validate type input
+        run: |
+          if [[ "${{ inputs.type }}" != "official" && "${{ inputs.type }}" != "experimental" ]]; then
+            echo "❌ Invalid input: 'type' must be 'official' or 'experimental'"
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
